FROM zironycho/pytorch:1120-cpu-py38

LABEL maintainer="Salil Gautam <salil.gtm@gmail.com>"
LABEL description="Dockerfile for Assignment 8 of EMLOv3 - VIT Gradio."

WORKDIR /workspace

COPY setup.py setup.py
COPY adamantium/ adamantium/
COPY configs/ configs/
COPY logs/train/runs/ logs/train/runs/

RUN pip install --no-cache-dir -r adamantium/demo/cifar10_jit/requirements.txt
RUN pip install -e .
RUN rm -rf /root/.cache/pip

EXPOSE 8080

CMD ["adamantium_demo_cifar10"]