FROM python:3.8-slim-buster

LABEL maintainer="Salil Gautam <salil.gtm@gmail.com>"
LABEL description="Dockerfile for Assignment 8 of EMLOv3 - VIT Gradio."

WORKDIR /workspace

COPY setup.py setup.py
COPY adamantium/ adamantium/
COPY configs/ configs/
COPY logs/ logs/

RUN pip install --no-cache-dir -r adamantium/demo/cifar10_jit/requirements.txt
RUN pip install --no-cache-dir -e .

EXPOSE 8080

CMD ["adamantium_demo_cifar10"]