# @package _global_

# specify here default configuration
# order of defaults determines the order in which configs override each other
defaults:
  - _self_
  - paths: default.yaml
  - logger: many_loggers.yaml
  - hydra: default.yaml

  - demo: cifar10_demo.yaml

# task name, determines output directory path
task_name: "demo"